version: '3'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
  fastapi:
    container_name: back_end
    build:
      context: back
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - DATASET_PATH=./images_project
      - EMBEDDINGS_FOLDER=embeddings
      - MODEL_ID=openai/clip-vit-base-patch32
      - QDRANT_URL=http://qdrant_container:6333
      - COLLECTION_NAME=image_search
      - MODEL_PARAMS_PATH=weights/optimized_model.pt
  front:
    build:
      context: front
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    environment:
      - REACT_APP_BACK_URL=http://localhost:8000
      - REACT_APP_IMAGES_URL=http://localhost:8000/images