version: '3'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
  fastapi:
    build:
      context: back
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - DATASET_PATH=./dataset
      - MODEL_ID=openai/clip-vit-base-patch32
      - QDRANT_URL=http://qdrant_container:6333